trigger:
- main

pool:
  vmImage: 'windows-latest'  # Cambiado a Windows

variables:
  buildConfiguration: 'Release'
  packagePath: '$(Build.ArtifactStagingDirectory)/publish'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x.x'  # Asegúrate de tener la versión correcta de .NET 8
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(packagePath)'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(packagePath)'
    artifactName: 'drop'
    publishLocation: 'Container'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '$(azureSubscription)'  # Referencia a la variable de conexión de servicio
    appType: 'webApp'
    appName: '$(appName)'  # Referencia a la variable del nombre del App Service
    package: '$(packagePath)'
    runtimeStack: 'DOTNET|8.0'  # Define el stack de .NET 8.0
    enableCustomDeployment: true
