trigger:
- main # Rama principal de tu repositorio

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  azureSubscription: 'serviceconnection-arp'
  appServiceName: 'app-arp-linux-westeu-001'
  resourceGroupName: 'rg-arp-westeu-001'
  projectName: 'AzureResourceProbes.API'
  vmImageName: 'ubuntu-latest'

steps:
  - task: UseDotNet@2
    displayName: 'Instalar .NET SDK 8.x'
    inputs:
      packageType: 'sdk'
      version: '8.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: DotNetCoreCLI@2
    displayName: 'Restaurar paquetes NuGet'
    inputs:
      command: 'restore'
      projects: '**/$(projectName).csproj'

  - task: DotNetCoreCLI@2
    displayName: 'Compilar la aplicación'
    inputs:
      command: 'build'
      projects: '**/$(projectName).csproj'
      arguments: '--configuration $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: 'Publicar la aplicación'
    inputs:
      command: 'publish'
      projects: '**/$(projectName).csproj'
      arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publicar artefactos de compilación'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'

  - task: AzureWebApp@1
    displayName: 'Desplegar a Azure App Service'
    inputs:
      azureSubscription: $(azureSubscription)
      appType: 'webAppLinux'
      appName: $(appServiceName)
      package: '$(Build.ArtifactStagingDirectory)/*'
      resourceGroupName: $(resourceGroupName)
